server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphql
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  playground:
    enabled: true
    mapping: /playground
